services:
  - type: web
    name: portfolio
    env: node
    nodeVersion: "20"
    plan: free
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: yarn start -- -p $PORT
    autoDeploy: true
